# Language is PHP
language: php

# Attribs for PHP
php:
  - "5.4"

# Fix permissions first
before_script: "chmod -R 777 ."

# Run all tests in the unit tests directory
script: "cd tests && phpunit --bootstrap bootstrap.php --strict --colors ."
